# Generated by Django 5.0.3 on 2024-03-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='dastukebulia',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
