# Generated by Django 5.0.3 on 2024-04-13 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipes',
            name='created',
            field=models.DateField(auto_now_add=True),
        ),
    ]
